name: hgb-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - pytorch
  - torchvision
  - matplotlib
  - opencv
  - pillow
  - tqdm
  - jupyter
  - pip
  - pip:
      - albumentations
      - timm
      - torchmetrics
      - hydra-core